
{dede:noteinfo notename="39成人教育" channelid="1" macthtype="string"
refurl="http://" sourcelang="gb2312" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="hand" rssurl="http://" regxurl="http://"
startid="1" endid="" addv="1" urlrule="area"
 musthas=".html" nothas="" listpic="1" usemore="0"}
	{dede:addurls}http://sex.39.net/xjy/crxjy/index.html{/dede:addurls}
	{dede:batchrule}{/dede:batchrule}
	{dede:regxrule}{/dede:regxrule}
	{dede:areastart}<div class="newslist">{/dede:areastart}
	{dede:areaend}<div class="page">{/dede:areaend}
{/dede:listrule}

