<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/151221/1-1512210Z412.jpg ",93,239);
$z[1][4]['ddimg']="/uploads/allimg/151221/1-1512210Z412.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1200";
$z[1][4]['height']="700";
$z[2]=Array("img"," /uploads/allimg/151221/1-1512210Z415.jpg ",241,387);
$z[2][4]['ddimg']="/uploads/allimg/151221/1-1512210Z415.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1024";
$z[2][4]['height']="768";
$z[3]=Array("img"," /uploads/allimg/151221/1-1512210Z415-50.jpg ",389,540);
$z[3][4]['ddimg']="/uploads/allimg/151221/1-1512210Z415-50.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="550";
$z[3][4]['height']="245";

?>