{dede:noteinfo notename="仪器仪表行业新闻" channelid="1" macthtype="string"
refurl="http://news.machine365.com/newslist-dust-65.shtml" sourcelang="gb2312" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://news.machine365.com/newslist-dust-65-(*).shtml"
startid="1" endid="10" addv="1" urlrule="area"
 musthas="" nothas="" listpic="0" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<!--文章详细模块开始-->{/dede:areastart}
    {dede:areaend}<!--文章详细模块结束-->{/dede:areaend}
{/dede:listrule}
