<?php
$z[0]=Array("noteinfo","",0,215);
$z[0][4]['notename']="仪器仪表行业新闻";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://news.machine365.com/newslist-dust-65.shtml";
$z[0][4]['sourcelang']="gb2312";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<!--文章详细模块开始-->{/dede:areastart}\r\n    {dede:areaend}<!--文章详细模块结束-->{/dede:areaend}\r\n",219,694);
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://news.machine365.com/newslist-dust-65-(*).shtml";
$z[1][4]['startid']="1";
$z[1][4]['endid']="10";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="0";
$z[1][4]['usemore']="0";

?>