<?php
$z[0]=Array("sppage","",0,59);
$z[0][4]['sptype']="full";
$z[0][4]['srul']="1";
$z[0][4]['erul']="5";
$z[1]=Array("previewurl","http://news.machine365.com/newslist-dust-65.shtml",61,145);
$z[2]=Array("keywordtrim","",147,184);
$z[3]=Array("descriptiontrim","",186,231);
$z[4]=Array("item","\r\n   {dede:match}<div class=\"newliIn_ti\">[内容]</div>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",233,410);
$z[4][4]['field']="title";
$z[4][4]['value']="";
$z[4][4]['isunit']="";
$z[4][4]['isdown']="";
$z[5]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",410,550);
$z[5][4]['field']="writer";
$z[5][4]['value']="";
$z[5][4]['isunit']="";
$z[5][4]['isdown']="";
$z[6]=Array("item","\r\n   {dede:match}<div class=\"ArticleCnt\" id=\"ArticleCnt\">[内容]</div>{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",550,744);
$z[6][4]['field']="source";
$z[6][4]['value']="";
$z[6][4]['isunit']="";
$z[6][4]['isdown']="";
$z[7]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",744,885);
$z[7][4]['field']="pubdate";
$z[7][4]['value']="";
$z[7][4]['isunit']="";
$z[7][4]['isdown']="";
$z[8]=Array("item","\r\n   {dede:match}<div class=\"ArticleCnt\" id=\"ArticleCnt\">{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",885,1065);
$z[8][4]['field']="body";
$z[8][4]['value']="";
$z[8][4]['isunit']="1";
$z[8][4]['isdown']="1";

?>