{dede:noteinfo notename="仪器仪表行业新闻" channelid="1" macthtype="string"
    refurl="http://news.machine365.com/content/2015/1211/518602.html" sourcelang="gb2312" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://news.machine365.com/newslist-dust-65-(*).shtml"
startid="2" endid="10" addv="1" urlrule="area" musthas=".html"
 nothas="" listpic="0" usemore="0"}
    {dede:addurls}http://news.machine365.com/newslist-dust-65.shtml
{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div  class="guonei_01">
{/dede:areastart}
    {dede:areaend}<div  class="guonei_title">{/dede:areaend}
{/dede:listrule}
{dede:sppage sptype='full' srul='1' erul='5'}{/dede:sppage}
{dede:previewurl}http://news.machine365.com/content/2015/1211/518602.html{/dede:previewurl}
{dede:keywordtrim}{/dede:keywordtrim}
{dede:descriptiontrim}{/dede:descriptiontrim}
{dede:item field='title' value='' isunit='' isdown=''}
   {dede:match}<div class="newliIn_ti">[内容]</div>{/dede:match}
   
   {dede:function}{/dede:function}
{/dede:item}{dede:item field='writer' value='' isunit='' isdown=''}
   {dede:match}{/dede:match}
   
   {dede:function}{/dede:function}
{/dede:item}{dede:item field='source' value='' isunit='' isdown=''}
   {dede:match}{/dede:match}
   
   {dede:function}{/dede:function}
{/dede:item}{dede:item field='pubdate' value='' isunit='' isdown=''}
   {dede:match}{/dede:match}
   
   {dede:function}{/dede:function}
{/dede:item}{dede:item field='body' value='' isunit='1' isdown='1'}
   {dede:match}<div class="newliIn_Zti">[内容]</div>{/dede:match}
   
   {dede:function}{/dede:function}
{/dede:item}