<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/151221/1-151221104941.jpg ",93,240);
$z[1][4]['ddimg']="/uploads/allimg/151221/1-151221104941.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="640";
$z[1][4]['height']="170";
$z[2]=Array("img"," /uploads/allimg/151221/1-151221104941-50.jpg ",242,395);
$z[2][4]['ddimg']="/uploads/allimg/151221/1-151221104941-50.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="750";
$z[2][4]['height']="750";

?>