<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/151221/1-1512210Z014.jpg ",93,240);
$z[1][4]['ddimg']="/uploads/allimg/151221/1-1512210Z014.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="2211";
$z[1][4]['height']="1658";
$z[2]=Array("img"," /uploads/allimg/151221/1-1512210Z036.jpg ",242,389);
$z[2][4]['ddimg']="/uploads/allimg/151221/1-1512210Z036.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="2210";
$z[2][4]['height']="1658";
$z[3]=Array("img"," /uploads/allimg/151221/1-1512210Z053.jpg ",391,538);
$z[3][4]['ddimg']="/uploads/allimg/151221/1-1512210Z053.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1286";
$z[3][4]['height']="1714";

?>