
{dede:noteinfo notename="99½¡¿µÒûÊ³" channelid="1" macthtype="string"
refurl="http://" sourcelang="gb2312" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="hand" rssurl="http://" regxurl="http://"
startid="1" endid="" addv="1" urlrule="area"
 musthas=".html" nothas="yyxw" listpic="1" usemore="0"}
	{dede:addurls}http://www.99-jk.cn/html/ys/yyxw.html{/dede:addurls}
	{dede:batchrule}{/dede:batchrule}
	{dede:regxrule}{/dede:regxrule}
	{dede:areastart}<table width="100%" border="0">{/dede:areastart}
	{dede:areaend}</table>{/dede:areaend}
{/dede:listrule}

