<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/151221/1-151221091546.jpg ",93,240);
$z[1][4]['ddimg']="/uploads/allimg/151221/1-151221091546.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="466";
$z[1][4]['height']="450";
$z[2]=Array("img"," /uploads/allimg/151221/1-151221091548.jpg ",242,389);
$z[2][4]['ddimg']="/uploads/allimg/151221/1-151221091548.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="480";
$z[2][4]['height']="480";
$z[3]=Array("img"," /uploads/allimg/151221/1-151221091550.jpg ",391,538);
$z[3][4]['ddimg']="/uploads/allimg/151221/1-151221091550.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="488";
$z[3][4]['height']="430";

?>