{dede:noteinfo notename="仪器仪表行业新闻" channelid="1" macthtype="string"
    refurl="http://" sourcelang="gb2312" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://news.machine365.com/newslist-dust-65-(*).shtml"
startid="2" endid="10" addv="1" urlrule="area" musthas=".html"
 nothas="" listpic="0" usemore="0"}
    {dede:addurls}http://news.machine365.com/newslist-dust-65.shtml
{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div  class="guonei_01">
{/dede:areastart}
    {dede:areaend} <div  class="guonei_title">{/dede:areaend}
{/dede:listrule}
