{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='1'/}
{dede:img ddimg='/uploads/allimg/151221/1-1512210U648.jpg' text='' width='750' height='443'} /uploads/allimg/151221/1-1512210U648.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/151221/1-1512210U649.jpg' text='' width='1136' height='852'} /uploads/allimg/151221/1-1512210U649.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/151221/1-1512210UA0.jpg' text='' width='750' height='750'} /uploads/allimg/151221/1-1512210UA0.jpg {/dede:img}
