<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/151221/1-1512210U648.jpg ",93,238);
$z[1][4]['ddimg']="/uploads/allimg/151221/1-1512210U648.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="750";
$z[1][4]['height']="443";
$z[2]=Array("img"," /uploads/allimg/151221/1-1512210U649.jpg ",240,386);
$z[2][4]['ddimg']="/uploads/allimg/151221/1-1512210U649.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1136";
$z[2][4]['height']="852";
$z[3]=Array("img"," /uploads/allimg/151221/1-1512210UA0.jpg ",388,531);
$z[3][4]['ddimg']="/uploads/allimg/151221/1-1512210UA0.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="750";
$z[3][4]['height']="750";

?>