<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/151221/1-1512210U138.jpg ",93,238);
$z[1][4]['ddimg']="/uploads/allimg/151221/1-1512210U138.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="750";
$z[1][4]['height']="400";
$z[2]=Array("img"," /uploads/allimg/151221/1-1512210U139.jpg ",240,385);
$z[2][4]['ddimg']="/uploads/allimg/151221/1-1512210U139.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="750";
$z[2][4]['height']="750";
$z[3]=Array("img"," /uploads/allimg/151221/1-1512210U139-50.jpg ",387,538);
$z[3][4]['ddimg']="/uploads/allimg/151221/1-1512210U139-50.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="750";
$z[3][4]['height']="492";
$z[4]=Array("img"," /uploads/allimg/151221/1-1512210U140.jpg ",540,685);
$z[4][4]['ddimg']="/uploads/allimg/151221/1-1512210U140.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="750";
$z[4][4]['height']="444";
$z[5]=Array("img"," /uploads/allimg/151221/1-1512210U141.jpg ",687,832);
$z[5][4]['ddimg']="/uploads/allimg/151221/1-1512210U141.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="750";
$z[5][4]['height']="514";

?>