<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="1";
$z[1]=Array("img"," /uploads/allimg/151221/1-1512210T119.jpg ",93,238);
$z[1][4]['ddimg']="/uploads/allimg/151221/1-1512210T119.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="790";
$z[1][4]['height']="850";
$z[2]=Array("img"," /uploads/allimg/151221/1-1512210T125.jpg ",240,386);
$z[2][4]['ddimg']="/uploads/allimg/151221/1-1512210T125.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="790";
$z[2][4]['height']="1822";
$z[3]=Array("img"," /uploads/allimg/151221/1-1512210T130.jpg ",388,534);
$z[3][4]['ddimg']="/uploads/allimg/151221/1-1512210T130.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="790";
$z[3][4]['height']="2650";
$z[4]=Array("img"," /uploads/allimg/151221/1-1512210T133.jpg ",536,682);
$z[4][4]['ddimg']="/uploads/allimg/151221/1-1512210T133.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="790";
$z[4][4]['height']="1000";

?>