
<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:tel itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>

<field:email itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:mc itemname="公司名称" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mc>

<field:dz itemname="公司地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dz>

<field:dh itemname="公司电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dh>

<field:zcdz itemname="注册地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:zcdz>

<field:jj itemname="公司简介" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:jj>

<field:fw itemname="经营范围" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:fw>

<field:ls itemname="从业历史" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:ls>

<field:gh itemname="未来规划" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:gh>
