<?php
$z[0]=Array("noteinfo","",0,179);
$z[0][4]['notename']="仪器仪表行业新闻";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="regex";
$z[0][4]['refurl']="http://";
$z[0][4]['sourcelang']="gb2312";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}http://news.machine365.com/newslist-dust-65.shtml\r\n{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<div  class=\"guonei_01\">\r\n{/dede:areastart}\r\n    {dede:areaend}<div  class=\"guonei_title\">{/dede:areaend}\r\n",181,703);
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://news.machine365.com/newslist-dust-65-(*).shtml";
$z[1][4]['startid']="2";
$z[1][4]['endid']="10";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']=".html";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="0";
$z[1][4]['usemore']="0";

?>